In [3]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset("titanic")
df.head()
df=df[["survived","pclass","sex","embarked"]]
df.head()

   survived  pclass     sex embarked
0         0       3    male        S
1         1       1  female        C
2         1       3  female        S
3         1       1  female        S
4         0       3    male        S

In [12]:
from sklearn.preprocessing import OrdinalEncoder

ordinal = OrdinalEncoder(categories=[[1,2,3]])
df["pclass_encoded"]=ordinal.fit_transform(df[["pclass"]])
df.head()

   survived  pclass     sex embarked  pclass_encoded  pclass_encod
0         0       3    male        S             2.0             0
1         1       1  female        C             0.0             2
2         1       3  female        S             2.0             0
3         1       1  female        S             0.0             2
4         0       3    male        S             2.0             0

In [13]:
mapping={3:0, 2:1, 1:2}
df["pclass_encod"]=df["pclass"].map(mapping)
df.head

<bound method NDFrame.head of      survived  pclass     sex embarked  pclass_encoded  pclass_encod
0           0       3    male        S             2.0             0
1           1       1  female        C             0.0             2
2           1       3  female        S             2.0             0
3           1       1  female        S             0.0             2
4           0       3    male        S             2.0             0
..        ...     ...     ...      ...             ...           ...
886         0       2    male        S             1.0             1
887         1       1  female        S             0.0             2
888         0       3  female        S             2.0             0
889         1       1    male        C             0.0             2
890         0       3    male        Q             2.0             0

[891 rows x 6 columns]>